#!/usr/bin/env bash

set -euo pipefail

# AWS SM is only in very recent AWS CLI versions, and isn't on Amazon Linux 2 AMIs (as of July 2018)
docker pull infrastructureascode/aws-cli

function get_secret_value() {
  local secretId="$1"
  docker run \
    --rm \
    -v ~/.aws:/root/.aws \
    -e 'AWS_ACCESS_KEY_ID' \
    -e 'AWS_SECRET_ACCESS_KEY' \
    -e 'AWS_DEFAULT_REGION' \
    -e 'AWS_REGION' \
    -e 'AWS_SECURITY_TOKEN' \
    -e 'AWS_SESSION_TOKEN' \
    infrastructureascode/aws-cli \
    aws secretsmanager get-secret-value \
      --secret-id "${secretId}" \
      --version-stage AWSCURRENT \
      --output text \
      --query 'SecretString'
}

function strip_quotes() {
  echo "${1}" | sed "s/^[ \t]*//g;s/[ \t]*$//g;s/[\"']//g"
}

# parse env items
while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_SM_ENV_[0-9]+) ]] ; then
    IFS='=' read exportName secretId <<< "${!name}"
    trimmedName=$(strip_quotes "${exportName}")
    trimmedSecretId=$(strip_quotes "${secretId}")
    echo "--- :aws::key: Reading ${trimmedSecretId} from AWS SM into ${trimmedName}"
    value=$(get_secret_value "${trimmedSecretId}")
    export "${trimmedName}=${value}"
  fi
done < <(env | sort)
